#!/bin/zsh
while true
do
    echo "\e[32m-----------------"
    echo "'lsfile' File Lookup"
    echo "$(pwd) \e[0m"
    ls -AGF
    echo -n ":"
    read operation
    if [[ ${operation} = //* ]];then
        if [ ${operation:2} = "q" ];then
            break
        fi
        if [[ ${operation:2} = finder* ]];then
            open -R "./${operation:9}"
        else
            echo "\e[32mCommand not support:'${operation:2}'\e[0m"
        fi
    else
        cd ${operation}
    fi
    echo
done

